### ISSUE TITLE
CORS policy when using the library

### ISSUE THREAD

**Issue by jisraeltoledo** [Huskie/boxrec-client#2]
Access to fetch at 'http://boxrec.com/en/boxer/659461' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Huskie** [comment]
@jisraeltoledo this looks like you are making the requests from the browser. At the moment, the library is targeted at a Node environment where you would fetch the data server-side and store it, after which you can access this data client-side.

Given there is no proxy on the requests to BoxRec you wouldn't want to be using this library client-side in case of rate limiting/being IP blocked. Much better to gather all the data you need first and save it to your own store.
